# Generated by Django 4.2.7 on 2023-11-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='release_year',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
